services:
  backend:
    build:
      context: ./domain
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      APP_PORT: ${APP_PORT}
      WG_NET: ${WG_NET}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    depends_on:
      - postgres
    networks:
      - vpnnet

  frontend:
    build: ./frontend
    container_name: panel
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - vpnnet

  postgres:
    image: postgres:latest
    container_name: split-net-postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - vpnnet

volumes:
  pg_data:

networks:
  vpnnet:
    driver: bridge
