server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: split-net
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:split-name}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driverClassName: org.postgresql.Driver

  rabbitmq:
    host: 192.168.0.108
    port: 5672
    username: guest
    password: guest
    virtual-host: /

logging:
  level:
    com.kridan.split_net: DEBUG
    root: INFO

jwt:
  secret: "r8N3kPq7vY2sF1dL9hJ5wXzT6bQ4uV0m"

wg:
  url: ${URL:192.168.0.108}
  interface: wg0
  listenPort: ${WG_PORT}
  net: ${WG_NET}