spring:
    application:
        name: gateway
    datasource:
        url: jdbc:h2:file:/data/db
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    rabbitmq:
      host: 192.168.0.108
      port: 5672
      username: guest
      password: guest
      virtual-host: /

gateway:
  api: "http://192.168.0.108:8080"
  jwtToken: "dasafas"